In [21]:
import numpy as np
import tensorflow as tf
from PIL import Image

In [22]:
x = np.array(5)  # 0维张量/标量 ,就是一个数字
print(x)
x.ndim

5


0

In [23]:
y = np.array([x for x in range(5)]) # 1维张量/向量 ，一个数组
print(y)
y.ndim #查看有多少个坐标轴

[0 1 2 3 4]


1

In [20]:
file = tf.io.read_file('1.png')
tf.image.decode_image(file)

<tf.Tensor: id=18, shape=(70, 66, 4), dtype=uint8, numpy=
array([[[150, 129, 116, 255],
        [150, 130, 116, 255],
        [150, 130, 116, 255],
        ...,
        [138, 123, 113, 255],
        [141, 125, 117, 255],
        [140, 125, 117, 255]],

       [[150, 129, 116, 255],
        [150, 129, 116, 255],
        [150, 129, 116, 255],
        ...,
        [138, 123, 113, 255],
        [138, 123, 115, 255],
        [134, 118, 111, 255]],

       [[148, 130, 119, 255],
        [148, 130, 118, 255],
        [150, 130, 118, 255],
        ...,
        [137, 121, 114, 255],
        [132, 116, 106, 255],
        [131, 115, 105, 255]],

       ...,

       [[149, 150, 139, 255],
        [149, 150, 138, 255],
        [150, 151, 139, 255],
        ...,
        [158, 149, 140, 255],
        [159, 151, 142, 255],
        [158, 149, 140, 255]],

       [[149, 150, 138, 255],
        [149, 150, 139, 255],
        [149, 150, 138, 255],
        ...,
        [159, 151, 141, 255],
        [158, 15

In [26]:
file = tf.io.read_file('图标.png')
tf.image.decode_image(file)


<tf.Tensor: id=48, shape=(512, 512, 4), dtype=uint8, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)>